language: java

jdk:
    - oraclejdk8

before_script:
    - pip install --user codecov

script:
    - mvn install

after_success:
  - mvn coveralls:report -Ptravis
  - codecov

notifications:
    email:
      on_failure: change